{{ if not .Values.systemDefaultValues.disconnectedEnvironment.enabled}}
{{ if and (.Values.systemDefaultValues.resourceSyncAgent.enabled) (not .Values.systemDefaultValues.appliance.enabled) (eq .Values.global.cluster_type "provisionedclusters")}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: provisionedclusters.arc.azure.com
  labels:
    azuresync: "true"
  annotations:
    resourceSync.arc.azure.com/ProviderNamespace: {{ .Values.global.rpNamespace }}-metadata
    resourceSync.arc.azure.com/ResourceType: {{ .Values.global.cluster_type }}
  creationTimestamp: null
spec:
  group: arc.azure.com
  preserveUnknownFields: false
  names:
    kind: ProvisionedCluster
    plural: provisionedclusters
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: ProvisionedCluster is the object for the ProvisionedCluster's Metadata sync.
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ProvisionedClusterSpec defines the desired state of
              ProvisionedClusters
            properties:
              azureResourceId:
                description: AzureResourceId is the armId of the cluster
                type: string
            type: object
          status:
            description: ProvisionedClusterStatus defines the observed state
              of ProvisionedCluster's Arc related metadata.
            properties:
              {{- include "resourcesync.commonproperties" . | indent 14 }}
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
{{- end }}
{{ end }}