{{- if .Values.systemDefaultValues.guard.enabled }}
{{- if eq .Values.systemDefaultValues.guard.pkiHostPath "" }}
{{- $secret := (lookup "v1" "Secret" "azure-arc" "guard-pki-secret") -}}
{{- $ca := genCA "guard-ca" 3650 }}
apiVersion: v1
kind: Secret
metadata:
  name: guard-pki-secret
  namespace: azure-arc
type: Opaque
data:
{{- if $secret }}
  ca.crt: {{ index $secret.data "ca.crt" }}
  ca.key: {{ index $secret.data "ca.key" }}
{{- else }}
  ca.crt: {{ b64enc $ca.Cert }}
  ca.key: {{ b64enc $ca.Key }}
{{- end }}
{{- end }}
---
{{- if ne .Values.systemDefaultValues.guard.authnMode "arc" }}
apiVersion: v1
kind: Secret
metadata:
  name: guard-secret
  namespace: azure-arc
  labels:
    app.kubernetes.io/name: azure-arc-k8s
type: Opaque
data:
  client-secret: {{ .Values.systemDefaultValues.guard.clientSecret | b64enc }}
{{- end }}
{{- end }}