{{ if not .Values.systemDefaultValues.disconnectedEnvironment.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-fluentbit-collector-config
  namespace: azure-arc
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         120
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   Off

    @INCLUDE input.conf
    @INCLUDE filter.conf
    @INCLUDE output.conf

  input.conf: |
    [INPUT]
        Name              forward
        Listen            0.0.0.0
        Port              24224
        Buffer_Max_Size   1MB
        Buffer_Chunk_Size 100KB

    [INPUT]
        Name              tail
        Tag               azure-arc.logcollector.*
        Path              /var/log/con*/${POD_NAME}*azure-arc*.log
        Multiline         On
        Parser_Firstline  first_line
        Mem_Buf_Limit     100KB
        Buffer_Chunk_Size 1KB

  filter.conf: |
    [FILTER]
        Name lua
        Match azure-arc.logcollector.*
        script /fluent-bit/bin/helpers.lua
        call process

    [FILTER]
        Name record_modifier
        Match azure-arc.logcollector.*
        Record AgentNameOverride ${AGENT_NAME}

  parsers.conf: |
    [PARSER]
        Name        first_line
        Format      regex
        Regex       ^{"log":"(?!\\u0009)(?<log>\bpanic([^,"]|\n)*)"

  output.conf: |
    [OUTPUT]
        Name        http_mdm
        Match       *
        Id          http_mdm_plugin
{{ end }}