{{ if not .Values.systemDefaultValues.disconnectedEnvironment.enabled}}
{{ if .Values.systemDefaultValues.appliance.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appliance-connect-agent
  namespace: azure-arc
  labels:
    app.kubernetes.io/name:  azure-arc-k8s
    app.kubernetes.io/component: appliance-connect-agent
  annotations:
    description: {{ .Chart.Description }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azure-arc-k8s
      app.kubernetes.io/component: appliance-connect-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azure-arc-k8s
        app.kubernetes.io/component: appliance-connect-agent
      annotations:
        checksum/proxysecret: {{ include (print $.Template.BasePath "/azure-proxy-secret.yaml") . | sha256sum }}
        checksum/fluent-bit-config: {{ include (print $.Template.BasePath "/azure-fluentbit-config-appliance-connect-agent.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: azure-arc-operatorsa
{{- if .Values.systemDefaultValues.azureArcAgents.affinity }}
      affinity:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.affinity | indent 8 }}
{{- end }}
{{- if .Values.systemDefaultValues.azureArcAgents.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.systemDefaultValues.azureArcAgents.tolerations }}
      tolerations:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: appliance-connect-agent
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          image: "{{ .Values.systemDefaultValues.appliance.repository }}/{{ .Values.systemDefaultValues.image.releaseName }}/{{ index .Values.systemDefaultValues.appliance "connect-agent" "image" }}:{{ index .Values.systemDefaultValues.appliance "connect-agent" "tag" }}"
          imagePullPolicy: {{ .Values.systemDefaultValues.image.imagePullPolicy }}
{{- if .Values.systemDefaultValues.appliance.resources }}
          resources:
{{ toYaml .Values.systemDefaultValues.appliance.resources | indent 12 }}
{{- end }}
{{- if .Values.systemDefaultValues.appliance.aadauth.enabled }}
          args:
            - "--appliance-aad-enabled=true"
{{- end }}
          envFrom:
          - configMapRef:
              name: azure-clusterconfig
          {{ if .Values.global.isProxyEnabled }}
          - secretRef:
              name: proxy-config
          {{ end }}
          env:
          - name: APPLIANCE_DP_ENDPOINT_OVERRIDE
            value: {{ .Values.systemDefaultValues.appliance.appliance_dp_endpoint_override }}
          - name: APPLIANCE_CREATION_PARAMETERS_FOR_TELEMETRY
            value: {{ .Values.systemDefaultValues.appliance.appliance_creation_parameters_for_telemetry | toJson }}
          - name: AGENT_TYPE
            value: "ApplianceAgent"
          - name: AGENT_NAME
            value: "ApplianceConnectAgent"
          {{ if .Values.systemDefaultValues.IsDebug}}
          ports:
            - containerPort: 40000
              name: debug
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          {{end}}
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
          volumeMounts:
              - mountPath: /host-ssh-directory
                name: host-ssh-directory
{{- if and (or .Values.global.isCustomCert .Values.global.isProxyEnabled) (.Values.global.proxyCert) }}
              - name: ssl-certs
                mountPath: /etc/ssl/certs/
                readOnly: false
              - mountPath: /usr/local/share/ca-certificates/proxy-cert.crt
                subPath: proxy-cert.crt
                name: proxy-certstore
{{- end }}
        - name: fluent-bit
          image: "{{ .Values.systemDefaultValues.image.repository }}/{{ .Values.systemDefaultValues.image.releaseName }}/{{ index .Values.systemDefaultValues "fluent-bit" "image" }}:{{ index .Values.systemDefaultValues "fluent-bit" "tag" }}"
          imagePullPolicy: {{ .Values.systemDefaultValues.image.imagePullPolicy }}
          securityContext:
            readOnlyRootFilesystem: true
            {{ if eq .Values.global.kubernetesDistro "openshift" }}
            privileged: true
            {{end}}
            capabilities:
              drop:
                - ALL
{{ $fluentBit := index .Values.systemDefaultValues.appliance "connect-agent-fluent-bit" "resources" }}
{{- if  $fluentBit  }}
          resources:
{{ $fluentBit | toYaml | indent 12 }}
{{- end }}
          envFrom:
            - configMapRef:
                name: azure-clusterconfig
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_TYPE
              value: "ApplianceAgent"
            - name: AGENT_NAME
              value: "ApplianceConnectAgent"
          volumeMounts:
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: {{ index .Values.systemDefaultValues "fluent-bit" "containerLogPath" }}
            readOnly: true
          - name: fluentbit-clusterconfig
            mountPath: /fluent-bit/etc/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: {{ index .Values.systemDefaultValues "fluent-bit" "containerLogPath" }}
        - name: fluentbit-clusterconfig
          configMap:
            name: azure-fluentbit-config-appliance-connect-agent
        - name: host-ssh-directory
          hostPath:
            path: /home/clouduser/.ssh
{{- if and (or .Values.global.isCustomCert .Values.global.isProxyEnabled) (.Values.global.proxyCert) }}
        - name: proxy-certstore
          secret:
            secretName: proxy-cert
        - name: ssl-certs
          emptyDir: {}
{{- end }}
{{- end }}
{{ end }}