{{ if .Values.systemDefaultValues.optIn.ManagedIdentityAuth }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusteridentityoperator
  namespace: azure-arc
  labels:
    control-plane: cluster-identity-manager
    app.kubernetes.io/name: azure-arc-k8s
    app.kubernetes.io/component: cluster-identity-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: cluster-identity-manager
  template:
    metadata:
      labels:
        control-plane: cluster-identity-manager
        app.kubernetes.io/name: azure-arc-k8s
        app.kubernetes.io/component: cluster-identity-operator
      annotations:
        checksum/proxysecret: {{ include (print $.Template.BasePath "/azure-proxy-secret.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/azureconfig: {{ include (print $.Template.BasePath "/azure-config.yaml") . | sha256sum }}
        checksum/fluent-bit-config: {{ include (print $.Template.BasePath "/azure-fluentbit-config.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName:
        {{- include "platformserviceaccount.name" . | indent 8 }}
{{- if or .Values.systemDefaultValues.azureArcAgents.tolerations (eq .Values.global.cluster_type "provisionedclusters") }}
      tolerations:
{{- if eq .Values.global.cluster_type "provisionedclusters" }}
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
{{- end }}
{{- if .Values.systemDefaultValues.azureArcAgents.tolerations }}
{{ toYaml .Values.systemDefaultValues.azureArcAgents.tolerations | indent 8 }}
{{- end }}
{{- end}}
{{- if .Values.systemDefaultValues.azureArcAgents.affinity }}
      affinity:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.affinity | indent 8 }}
{{- end }}
{{- if .Values.systemDefaultValues.azureArcAgents.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.nodeSelector | indent 8 }}
{{- end }}
      hostIPC: false
      hostPID: false
      hostNetwork: false
      containers:
        - name: manager
          {{if .Values.systemDefaultValues.IsIdentityDebug}}
          args:
            - "--listen=:40000"
            - "--headless=true"
            - "--api-version=2"
            - "exec"
            - "/data/identityOperator"
            - "--"
            - "--metrics-addr=127.0.0.1:8080"
            - "--enable-leader-election"
          command:
          - /dlv
          {{end}}
          image: "{{ .Values.systemDefaultValues.image.repository }}/{{ .Values.systemDefaultValues.image.releaseName }}/{{ index .Values.systemDefaultValues "clusteridentityoperator" "image" }}:{{ index .Values.systemDefaultValues "clusteridentityoperator" "tag" }}"
          imagePullPolicy: {{ .Values.systemDefaultValues.image.imagePullPolicy }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {{if .Values.systemDefaultValues.clusteridentityoperator.his_endpoint_override}}
          - name: HIS_ENDPOINT
            value: {{.Values.systemDefaultValues.clusteridentityoperator.his_endpoint_override}}
          {{end}}
          envFrom:
          - configMapRef:
              name: azure-clusterconfig
          {{ if .Values.global.isProxyEnabled }}
          - secretRef:
              name: proxy-config
          {{ end }}
          {{if .Values.systemDefaultValues.clusteridentityoperator.armIdOverride}}
          env:
          - name: AZURE_RESOURCE_NAME
            value:  {{.Values.systemDefaultValues.clusteridentityoperator.resourceName}}
          - name: AZURE_SUBSCRIPTION_ID
            value:  {{ .Values.systemDefaultValues.clusteridentityoperator.subscription}}
          - name: AZURE_RESOURCE_GROUP
            value:  {{ .Values.systemDefaultValues.clusteridentityoperator.resourceGroup}}
          - name: ONBOARDING_SECRET_NAME
            value:  {{ .Values.systemDefaultValues.clusteridentityoperator.secretName}}
          - name: ONBOARDING_SECRET_NAMESPACE
            value:  {{ .Values.systemDefaultValues.clusteridentityoperator.secretNamespace}}
          {{end}}
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: {{ .Values.global.containerUser}}
            runAsGroup: {{ .Values.global.containerGroup}}
          {{ if .Values.systemDefaultValues.IsIdentityDebug}}
          ports:
            - containerPort: 40000
              name: debug
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          {{end}}
          {{- if and (or .Values.global.isCustomCert .Values.global.isProxyEnabled) (.Values.global.proxyCert) }}
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/
              readOnly: false
            - mountPath: /usr/local/share/ca-certificates/proxy-cert.crt
              subPath: proxy-cert.crt
              name: proxy-certstore
          {{- end }}
{{ if not .Values.systemDefaultValues.disconnectedEnvironment.enabled}}
        - name: fluent-bit
          image: "{{ .Values.systemDefaultValues.image.repository }}/{{ .Values.systemDefaultValues.image.releaseName }}/{{ index .Values.systemDefaultValues "fluent-bit" "image" }}:{{ index .Values.systemDefaultValues "fluent-bit" "tag" }}"
          imagePullPolicy: {{ .Values.systemDefaultValues.image.imagePullPolicy }}
          securityContext:
            readOnlyRootFilesystem: true
            {{ if eq .Values.global.kubernetesDistro "openshift" }}
            privileged: true
            {{end}}
            capabilities:
              drop:
                - ALL
{{ $fluentBit := index .Values.systemDefaultValues "fluent-bit" "resources" }}
{{- if  $fluentBit  }}
          resources:
{{ $fluentBit | toYaml | indent 12 }}
{{- end }}
          envFrom:
            - configMapRef:
                name: azure-clusterconfig
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_TYPE
              value: "ConfigAgent"
            - name: AGENT_NAME
              value: "IdentityController"
          volumeMounts:
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: {{ index .Values.systemDefaultValues "fluent-bit" "containerLogPath" }}
            readOnly: true
          - name: fluentbit-clusterconfig
            mountPath: /fluent-bit/etc/
{{ end }}
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: {{ index .Values.systemDefaultValues "fluent-bit" "containerLogPath" }}
        - name: fluentbit-clusterconfig
          configMap:
            name: azure-fluentbit-config
{{- if and (or .Values.global.isCustomCert .Values.global.isProxyEnabled) (.Values.global.proxyCert) }}
        - name: proxy-certstore
          secret:
            secretName: proxy-cert
        - name: ssl-certs
          emptyDir: {}
{{- end }}
      terminationGracePeriodSeconds: 10
---
{{ end }}
