{{ if not .Values.systemDefaultValues.disconnectedEnvironment.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-telegraf-config
  namespace: azure-arc
data:
  telegraf.conf: |
{{ (tpl ( .Files.Get "config/telegraf-conf.tmpl") .) | indent 4 }}
{{ end }}