{{- if .Values.global.isProxyEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: proxy-config
  namespace: azure-arc
type: Opaque
data:
  {{- if .Values.global.httpProxy }}
    HTTP_PROXY: {{.Values.global.httpProxy | b64enc | quote}}
  {{end}}
  {{- if .Values.global.httpsProxy }}
    HTTPS_PROXY: {{.Values.global.httpsProxy | b64enc | quote}}
  {{end}}
  {{- if .Values.global.noProxy }}
    NO_PROXY: {{.Values.global.noProxy| b64enc | quote}}
  {{end}}
{{- end }}
---
{{- if and (or .Values.global.isCustomCert .Values.global.isProxyEnabled) (.Values.global.proxyCert) }}
apiVersion: v1
kind: Secret
metadata:
  name: proxy-cert
  namespace: azure-arc
type: Opaque
data: 
  proxy-cert.crt: {{.Values.global.proxyCert | b64enc | quote}}
{{- end }}
