apiVersion: apps/v1
kind: Deployment
metadata:
  name: logcollector
  namespace: azure-arc
  labels:
    app.kubernetes.io/name: azure-arc-k8s
    app.kubernetes.io/component: logcollector
  annotations:
    description: {{ .Chart.Description }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azure-arc-k8s
      app.kubernetes.io/component: logcollector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azure-arc-k8s
        app.kubernetes.io/component: logcollector
      annotations:
        checksum/proxysecret: {{ include (print $.Template.BasePath "/azure-proxy-secret.yaml") . | sha256sum }}
        checksum/fluent-bit-config: {{ include (print $.Template.BasePath "/azure-fluentbit-collector-config.yaml") . | sha256sum }}
    spec:
      serviceAccountName:
        {{- include "platformserviceaccount.name" . | indent 8 }}
      hostIPC: false
      hostPID: false
      hostNetwork: false
{{- if .Values.systemDefaultValues.azureArcAgents.affinity }}
      affinity:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.affinity | indent 8 }}
{{- end }}
{{- if .Values.systemDefaultValues.azureArcAgents.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.systemDefaultValues.azureArcAgents.tolerations }}
      tolerations:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: fluent-bit
          image: "{{ .Values.systemDefaultValues.image.repository }}/{{ .Values.systemDefaultValues.image.releaseName }}/{{ index .Values.systemDefaultValues "fluent-bit-collector" "image" }}:{{ index .Values.systemDefaultValues "fluent-bit-collector" "tag" }}"
          imagePullPolicy: {{ .Values.systemDefaultValues.image.imagePullPolicy }}
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
{{ $fluentBit := index .Values.systemDefaultValues "fluent-bit" "resources" }}
{{- if  $fluentBit  }}
          resources:
{{ $fluentBit | toYaml | indent 12 }}
{{- end }}
          envFrom:
            - configMapRef:
                name: azure-clusterconfig
          {{ if .Values.global.isProxyEnabled }}
            - secretRef:
                name: proxy-config
          {{ end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_TYPE
              value: "ConnectAgent"
            - name: AGENT_NAME
              value: "LogCollector"
          volumeMounts:
          - name: fluentbit-clusterconfig
            mountPath: /fluent-bit/etc/
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: {{ index .Values.systemDefaultValues "fluent-bit" "containerLogPath" }}
            readOnly: true
{{- if and (or .Values.global.isCustomCert .Values.global.isProxyEnabled) (.Values.global.proxyCert) }}
          - name: ssl-certs
            mountPath: /etc/ssl/certs/
            readOnly: false
{{- end }}
      volumes:
        - name: fluentbit-clusterconfig
          configMap:
            name: azure-fluentbit-collector-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: {{ index .Values.systemDefaultValues "fluent-bit" "containerLogPath" }}
{{- if and (or .Values.global.isCustomCert .Values.global.isProxyEnabled) (.Values.global.proxyCert) }}
        - name: proxy-certstore
          secret:
            secretName: proxy-cert
        - name: ssl-certs
          emptyDir: {}
{{- end }}
