{{ if not .Values.global.isLeastPrivilegesMode }}
apiVersion: v1
kind: Namespace
metadata:
  name: azure-arc
  labels:
    control-plane: "true"
    admission.policy.azure.com/ignore: "true"
{{ end }}
