{{- if eq .Values.systemDefaultValues.noAuthHeaderDataPlane false}}
{{- if and (.Values.systemDefaultValues.spnOnboarding ) (not .Values.systemDefaultValues.appliance.enabled)}}
apiVersion: v1
kind: Secret
metadata:
  name: azure-arc-onboarding
  namespace: azure-arc
type: Opaque
data:
  value: {{ .Values.global.clientSecret | b64enc }}
{{- end }}
---
{{- if and (not .Values.systemDefaultValues.spnOnboarding) (not .Values.systemDefaultValues.appliance.enabled)}}
apiVersion: v1
kind: Secret
metadata:
  name: azure-arc-connect-privatekey
  namespace: azure-arc
type: Opaque
stringData: 
   privateKey: {{ .Values.global.onboardingPrivateKey | quote }}
{{- end }}
{{ if not .Values.systemDefaultValues.disconnectedEnvironment.enabled}}
---
{{ if or (and (index .Values.systemDefaultValues "clusterconnect-agent"  "enabled") (eq .Values.global.azureEnvironment "AZUREDOGFOOD") (not .Values.systemDefaultValues.appliance.enabled)) (eq .Values.global.cluster_type "provisionedclusters") }}
{{ $ca := genCA "azure-arc-ca" 3650 }}
{{ $cn := "kube-aad-proxy.azure-arc.svc.cluster.local" }}
{{ $server := genSignedCert $cn nil nil 3650 $ca }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: kube-aad-proxy-certificate
  namespace: azure-arc
data:
  tls.crt: {{ b64enc $server.Cert }}
  tls.key: {{ b64enc $server.Key }}
{{- end }}
---
{{ if .Values.systemDefaultValues.customIdentityProviderEnabled }}
{{ $ca := genCA "azure-arc-ca" 3650 }}
{{ $cn :=  "kube-aad-proxy.azure-arc.svc.cluster.local" }}
{{ $san :=  .Values.global.kubeAadEndpoint }}
{{ $server := genSignedCert "autonomous" nil (list $san) 3650 $ca }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: kube-aad-proxy-certificate
  namespace: azure-arc
data:
  tls.crt: {{ b64enc $server.Cert }}
  tls.key: {{ b64enc $server.Key }}
{{- end }}
{{- end }}
{{ end }}